fakesearch/urls.py
from django.conf.urls import patterns, url
from fakesearch import views

app_name = 'fakesearch'
urlpatterns = [ url(r'^$', views.index, name='index'),
                       url(r'^about/$', views.about, name='about'),

                       # Login related functions:
                       url(r'^register/$', views.register, name='register'),
                       url(r'^login/$', views.user_login, name='login'),
                       url(r'^logout/$', views.user_logout, name='logout'),
                       url(r'^profile/$', views.user_profile, name='profile'),

                       # Experiment related functions:
                       url(r'^experiments/$', views.experiments, name='experiments'),
                       url(r'^run_experiment/(?P<exp_pk>[\w]+)/', views.run_experiment, name='run_experiment'),
              ]

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^fakesearch/', include('fakesearch.urls', namespace="fakesearch")),
]

fakesearch/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

EXPERTISE_CHOICES = (
    (1, 'Layperson'),
    (2, 'Some Knowledge'),
    (3, 'Expert'),
)

LIST_PREFERENCE = (
    (1, 'Left Better'),
    (2, 'Equal'),
    (3, 'Right Better'),
)

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)
    expertise = models.IntegerField(default=-1)

    def __unicode__(self):
        return self.user.username

class Query(models.Model):
    qid = models.CharField(max_length=32)
    text = models.CharField(max_length=512)

    def __unicode__(self):
        return self.qid

class Document(models.Model):
    docname = models.CharField(max_length=32)
    title   = models.CharField(max_length=128)
    url     = models.URLField()
    snippet = models.CharField(max_length=512)

    def __unicode__(self):
        return self.docname

class ResultList(models.Model):
    description = models.CharField(max_length=128, default="-")
    doclist = models.ManyToManyField(Document, through='ListOrder')

    def __unicode__(self):
        return self.description

class ListOrder(models.Model):
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    resultlist = models.ForeignKey(ResultList, on_delete=models.CASCADE)
    rank = models.IntegerField()
    def __unicode__(self):
        return "%s, %s, %d" % (self.document.docname, self.resultlist.description, self.rank)

class Experiment(models.Model):
    # expid = models.CharField(max_length=128) # maybe a experiment description for human beings
    query = models.ForeignKey(Query)
    result_listA = models.ForeignKey(ResultList, null=True, related_name='listA')
    result_listB = models.ForeignKey(ResultList, null=True, related_name='listB')

    def __unicode__(self):
        return "%s,%s,%s" % (self.query.qid, self.result_listA, self.result_listB)

class ExperimentSet(models.Model):
    description = models.CharField(max_length=256)
    experiments = models.ManyToManyField(Experiment)

class UserExperimentSet(models.Model):
    user = models.ForeignKey(UserProfile)
    experimentSet = models.ForeignKey(ExperimentSet)

class Vote(models.Model):
    user = models.ForeignKey(UserProfile)
    experiment = models.ForeignKey(Experiment)
    preference = models.IntegerField(default=-1)

    def user_preference(self):
        return dict(LIST_PREFERENCE)[self.preference]

fakesearch/forms.py
from django import forms
from fakesearch.models import Experiment, UserProfile, ResultList, Vote, EXPERTISE_CHOICES, LIST_PREFERENCE
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')

class UserProfileForm(forms.ModelForm):
    expertise = forms.ChoiceField(widget=forms.RadioSelect, choices=EXPERTISE_CHOICES)

    class Meta:
        model = UserProfile
        fields = ('expertise',)

class VoteForm(forms.ModelForm):
    preference = forms.ChoiceField(widget=forms.RadioSelect, choices=LIST_PREFERENCE)

    class Meta:
        model = Vote
        fields = ('preference',)

fakesearch/views.py
# Login control
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# Django control
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
# FakeSearch classes
from fakesearch.models import ResultList, UserProfile, Experiment, ExperimentSet, Vote, UserExperimentSet
from fakesearch.forms import UserForm, UserProfileForm, VoteForm

#####
#### General screens
#####

def index(request):
    # Render the response and send it back!
    return render(request, 'fakesearch/index.html', {})

def about(request):
    return render(request, 'fakesearch/about.html', [])

#####
#### User authentification screens
#####
def register(request):

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True

            # Logs in the user now:
            new_user = authenticate(username=request.POST['username'], password=request.POST['password'])
            login(request, new_user)

            set_user_experiment_set(profile)

            return HttpResponseRedirect('/fakesearch/')

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print user_form.errors, profile_form.errors

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request,
            'fakesearch/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered} )

def user_login(request):

    disable_account = False
    bad_details = False

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
                # We use request.POST.get('<variable>') as opposed to request.POST['<variable>'],
                # because the request.POST.get('<variable>') returns None, if the value does not exist,
                # while the request.POST['<variable>'] will raise key error exception

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect('/fakesearch/')
            else:
                disable_account = True
                # An inactive account was used - no logging in!
        else:
            bad_details = True
            print "Invalid login details: {0}, {1}".format(username, password)

    return render(request, 'fakesearch/login.html', {'bad_details':bad_details, 'disable_account': disable_account})

# Use the login_required() decorator to ensure only those logged in can access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage.
    return HttpResponseRedirect('/fakesearch/')

def user_profile(request):
    # Render the response and send it back!
    return render(request, 'fakesearch/profile.html', {})


def set_user_experiment_set(user):
    # Gets a random Experient Set
    es = ExperimentSet.objects.order_by('?').first()
    ues = UserExperimentSet.objects.create(user=user, experimentSet=es)
    ues.save()

    # Add votes:
    for e in es.experiments.get_queryset():
        v, created = Vote.objects.get_or_create(user=user, experiment=e)
        v.preference = -1
        v.save()

#####
#### Experiments
#####
@login_required
def experiments(request):
    context = RequestContext(request)
    u = User.objects.get(username=request.user)
    try:
        up = UserProfile.objects.get(user=u)
    except:
        up = None

    experiment_list = []
    experiment_set = None
    ues = UserExperimentSet.objects.get(user=up)

    if ues:
        experiment_set = ues.experimentSet.experiments

    if experiment_set:
        experiments = experiment_set.order_by("pk")
        for experiment in experiments:
            try:
                preference = Vote.objects.get(user=up, experiment=experiment).preference
            except:
                preference = -1
            experiment_list.append((experiment, preference))

    else:
        print "Not Found"

    context_dict = {'experiments': experiment_list}

    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render(request, 'fakesearch/experiments.html', context_dict)

@login_required
def run_experiment(request, exp_pk):

    context = RequestContext(request)
    u = User.objects.get(username=request.user)
    try:
        up = UserProfile.objects.get(user=u)
    except:
        up = None

    e = get_object_or_404(Experiment, pk=exp_pk)
    v = get_object_or_404(Vote, experiment=e, user=up)

    def getNeighbor(e, up, variation):
        try:
            return UserExperimentSet.objects.get(user=up).experimentSet.experiments.get(pk = e.id + variation)
        except:
            return None
    next_exp = getNeighbor(e, up, +1)
    previous_exp = getNeighbor(e, up, -1)

    context_dict = {'experiment' : e, 'next_exp': next_exp, 'previous_exp': previous_exp, 'vote': v}

    if request.method == 'POST':

        vote_form = VoteForm(data=request.POST, instance=v)
        if vote_form.is_valid():
            vote_instance = vote_form.save()

        if 'next' in request.POST:
            e = next_exp
        if 'previous' in request.POST:
            e = previous_exp
        if 'done' in request.POST:
            return HttpResponseRedirect(reverse('fakesearch:experiments'))
        return HttpResponseRedirect(reverse('fakesearch:run_experiment', args=(e.id,)))

    # it is just the GET method:
    else:
        data_dict = {'preference': v.preference}
        context_dict['vote_form'] = VoteForm(initial=data_dict)

    return render(request, 'fakesearch/run_experiment.html', context_dict)

templates/fakesearch/about.html
{% extends "fakesearch/base.html" %}

{% block title %}FakeSearch{% endblock %}

{% block active_menu %}
    <li><a href="{% url 'fakesearch:index' %}">Home</a></li>
    <li class="active"><a href="{% url 'fakesearch:about' %}">About</a></li>
    {% if user.is_authenticated %}
        <li><a href="{% url 'fakesearch:experiments' %}">Experiments</a></li>
    {% endif %}
{% endblock %}

{% block body_block %}

    <div class="jumbotron">
        <p> Made with love from <a href="mailto:joaopalotti@gmail.com" target="_top">Joao Palotti</a> and Guido Zuccon. </p>
    </div>

{% endblock %}

templates/fakesearch/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en" hola_ext_inject="disabled" class="gr__getbootstrap_com">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <link rel="icon" href="http://33charts.com/wp-content/uploads/2011/04/search.png">

    {% block title_block %}
        <title>FakeSearch</title>
    {% endblock %}
    
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="https://getbootstrap.com/examples/starter-template/starter-template.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/fakesearch.css' %}">
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'fakesearch:index' %}">Fake Search</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                {% block active_menu %}
                    <li class="active"><a href="{% url 'fakesearch:index' %}">Home</a></li>
                    <li><a href="{% url 'fakesearch:about' %}">About</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'fakesearch:experiments' %}">Experiments</a></li>
                    {% endif %}
                {% endblock %}
            </ul>

            {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'fakesearch:profile' %}"><span class="glyphicon glyphicon-cog" aria-hidden=true></span> Settings</a></li>
                    <li><a href="{% url 'fakesearch:logout' %}">Logout</a></li>
                </ul>
            {% endif %}
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container">
    <div class="starter-template">

        {% block body_block %}
        <!-- Enter here whatever you want to customize -->
        {% endblock %}

    </div>
</div><!-- /.container -->


<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="http://getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>

</body>
<span class="gr__tooltip">
    <span class="gr__tooltip-content"></span>
    <i class="gr__tooltip-logo"></i>
    <span class="gr__triangle"></span>
</span>
</html>

templates/fakesearch/experiments.html
{% extends "fakesearch/base.html" %}

{% block title %} Experiments {% endblock %}

{% block active_menu %}
    <li><a href="{% url 'fakesearch:index' %}">Home</a></li>
    <li><a href="{% url 'fakesearch:about' %}">About</a></li>
    <li class="active"><a href="{% url 'fakesearch:experiments' %}">Experiments</a></li>
{% endblock %}

{% block body_block %}        
    {% if not user.is_authenticated %}
        <div class="jumbotron">
            <p> <strong> Please register to use this resource! </strong> </p>
        </div>
    {% endif %}

    {% if experiments %}
        <div class="jumbotron">
        <div class="panel panel-default">
    
        <div class="list-group">
            <a href="#" class="list-group-item active">
                Experiments
            </a>
            {% for experiment in experiments %}
                <a class="list-group-item" href="{% url 'fakesearch:run_experiment' experiment.0.id %}"> Experiment {{forloop.counter}}
                {% if experiment.1 < 0 %}
                    &nbsp  &nbsp  &nbsp <span class="label label-danger">ToDo <span class="glyphicon glyphicon-pencil" aria-hidden=true> </span> </span>
                {% else %}
                    &nbsp  &nbsp  &nbsp<span class="label label-success">Done <span class="glyphicon glyphicon-ok-sign" aria-hidden=true> </span></span>
                {% endif %}
                </a> 
            {% endfor %}
        </div>
        </div>
        </div>
    {% else %}
        <div class="jumbotron">
            <p> <strong> No experiments are set up for you!!! </strong> </p>
        </div>
    {% endif %}
{% endblock %}

templates/fakesearch/index.html
{% extends "fakesearch/base.html" %}

{% block title %}FakeSearch{% endblock %}

{% block active_menu %}
    <li class="active"><a href="{% url 'fakesearch:index' %}">Home</a></li>
    <li><a href="{% url 'fakesearch:about' %}">About</a></li>
    {% if user.is_authenticated %}
        <li><a href="{% url 'fakesearch:experiments' %}">Experiments</a></li>
    {% endif %}
{% endblock %}

{% block body_block %}

    <div class="jumbotron">
    {% if user.is_authenticated %}
        <h1>Hey {{ user.username }}!</h1>
        <h2> Let's start the <a href="{% url 'fakesearch:experiments' %}">experiments!</a> </h2>
    {% else %}
        <h1>Welcome to FakeSearch!</h1>
        <p> Please <a href="{% url 'fakesearch:login' %}">log in here</a> to start.<br /> </p>
        <p> If you don't have a login yet, <a href="{% url 'fakesearch:register' %}">register here</a><br /> </p>
    {% endif %}

    </div>

{% endblock %}

templates/fakesearch/login.html
{% extends "fakesearch/base.html" %}

{% block title %}Login to FakeSearch{% endblock %}

{% block body_block %}
<div class="jumbotron">
    <form class="form" id="login_form" method="post" action="{% url 'fakesearch:login' %}">

            {% if bad_details %}
            <div class="alert alert-danger" role="alert">
                <p><strong>Your username and/or password were incorrect!</strong></p>
            </div>
            {% elif disabled_account %}
            <p><strong>Your Rango account is currently disabled; we can't log you in!</strong></p>
            {% endif %}

            {% csrf_token %}
            <p> Username: <input class="input-block-level" type="text" name="username" value="" size="50" /></p>
            <p> Password: <input type="password" name="password" value="" size="50" /></p>
            <input class="btn btn-primary" type="submit" value="Log me in!" />
        </form>
    <br/>
    <p> Not registered yet? <a href="{% url 'fakesearch:register' %}">Register Here</a> </p>
</div>
{% endblock %}

templates/fakesearch/profile.html
{% extends "fakesearch/base.html" %}

{% block title %}User Profile{% endblock %}

{% block body_block %}
<div class="jumbotron">
    <p> Sorry.... it still needs to be done. </p>
</div>
{% endblock %}

templates/fakesearch/register.html
{% extends "fakesearch/base.html" %}
{% block title %}Register with FakeSearch{% endblock %}
    
{% block body_block %}
    
    <div class="jumbotron">
    {% if registered %}
        <strong>Thank you for registering!</strong>
        <a href="{% url 'fakesearch:index' %}">Return to the homepage.</a><br />
    {% else %}
       <form class="form" id="user_form" method="post" action="{% url 'fakesearch:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form  }}
            <br/>
            <br/>
            <p> Medical Expertise </p> 
            <div class="btn-group" data-toggle="buttons">
                {{ profile_form.expertise.errors }}
                {% for choice in profile_form.expertise %}
                    <label class="btn btn-primary ">
                        {{ choice.tag }}
                        {{ choice.choice_label }}
                    </label>
                {% endfor %}
            </div>
            <br/>
            <br/>
            <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span> Register
            </button>
        </form>
    {% endif %}
    </div>

{% endblock %}

templates/fakesearch/run_experiment.html
{% extends "fakesearch/base.html" %}

{% block title %} Running Experiment {% endblock %}

{% block active_menu %}
    <li><a href="{% url 'fakesearch:index' %}">Home</a></li>
    <li><a href="{% url 'fakesearch:about' %}">About</a></li>
    <li><a href="{% url 'fakesearch:experiments' %}">Experiments</a></li>
{% endblock %}


{% block body_block %}

{% if not user.is_authenticated %}
    <div class="jumbotron">
        <p> <strong> Please register to use this resource! </strong> </p>
    </div>
{% endif %}

{% if experiment %}
<div class="panel panel-default" id="external_panel">
    <div class="panel-heading"> 
        <input type="text" size=60 value="{{experiment.query.text}}" disabled=True>
        <img src="http://cdn.mysitemyway.com/icons-watermarks/simple-black/classica/classica_magnifying-glass-1/classica_magnifying-glass-1_simple-black_128x128.png" style="width:25px;height:25px;">
    </div>
    <div class="panel-body">
        <div class=row> 
            <!-- Left result list -->
            <div class="panel panel-default col-sm-6">
                <ul class="list-group" style="text-align: left">
                {% for document in experiment.result_listA.doclist.all %}
                <li class="list-group-item">
                <span class="doctitle"> {{document.title| truncatechars:50}}  </span> <br \>
                <span class="docurl"> {{document.url | truncatechars:60}} <br \> </span>
                    {{document.snippet| safe | truncatechars_html:200 }} <br \>
                </li>
                {% endfor %}
                </ul>
            </div>

            <!-- Right result list -->
            <div class="panel panel-default col-sm-6">
                <ul class="list-group" style="text-align: left">
                {% for document in experiment.result_listB.doclist.all %}
                <li class="list-group-item">
                <span class="doctitle"> {{document.title| truncatechars:50}}  </span> <br \>
                <span class="docurl"> {{document.url | truncatechars:60}} <br \> </span>
                    {{document.snippet | safe | truncatechars_html:200 }} <br \>
                </li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% else %}
    <strong> This experiment was not found. Please contact the admin! </strong>
{% endif %}
    
<form id="experiment_form" method="post" action="{% url 'fakesearch:run_experiment' experiment.id %}/">
    {% csrf_token %}
    <div class="btn-group" data-toggle="buttons">
        {% for choice in vote_form.preference %}
            {% if choice.choice_label == vote.user_preference %}
                <label class="btn btn-primary active">
            {% else %}
                <label class="btn btn-primary ">
            {% endif %}
                {{ choice.tag }}
                {{ choice.choice_label }}
         </label>
        {% endfor %}
    </div>
    <br/>
    <br/>
    {% if previous_exp %}
    <button type="submit" class="btn btn-primary" name="previous">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Vote & Back
    </button>
    {% endif %}
    {% if next_exp %}
    <button type="submit" class="btn btn-primary">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Vote
    </button>
    <button type="submit" class="btn btn-primary" name="next">
          Vote & Next <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> 
    </button>
    {% else %}
     <button type="submit" class="btn btn-primary" name="done">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Vote & Done
    </button>
    {% endif %}
</form>


{% endblock %}